# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-02-12 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u89c6\u9891\u5730\u5740'),
        ),
    ]
