# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-02-12 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190212_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_times',
            field=models.IntegerField(default=0, verbose_name='\u89c6\u9891\u65f6\u957f'),
        ),
    ]
