# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-02-17 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190110_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='index',
            field=models.IntegerField(default=100, verbose_name='\u987a\u5e8f'),
        ),
    ]
